spring:
  application:
    name: contract-audit
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_audit_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

python-pipeline:
  url: http://localhost:8001

jwt:
  secret: your_jwt_secret_key
  expiration: 900000
  refresh-expiration: 604800000

