spring:
  application:
    name: contract-audit
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_audit_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: spring-audit-result-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.project.contract_audit.kafka.*"




python:
  base.url: http://localhost:8001



jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: 900000
  refresh-expiration: 604800000


